baseURL = 'https://blog.philippbruhns.com/'
title = "Philipp's Blog"
author = 'Philipp Bruhns'
copyright = '© 2025, philippbruhns.com'
languageCode = 'en'
DefaultContentLanguage = 'en'
enableInlineShortcodes = true
theme = "paper"

[pagination]
    pagerSize = 5

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'YodaImperium'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'philippbruhns'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  # threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
  # bluesky = 'YOUR_BLUESKY_ID'               # https://bsky.app/profile/YOUR_BLUESKY_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'philipp.bruhns@protonmail.com'                 # gravatar email or image url
  name = 'Philipp B.'
  bio = 'This is my blog; see philippbruhns.com for more.'

  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = false                       # show monochrome dark mode icon
  gravatarCdn = 'https://avatars.githubusercontent.com/u/32957690?v=4'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "ltr"                         # RTL support for Right-to-left languages

  # giscus
[params.giscus]
  repo = 'YodaImperium/blogpersonal'                 # see https://giscus.app for more details
  repoId = 'R_kgDOPbtD8A'
  category = 'Giscus'
  categoryId = 'DIC_kwDOPbtD8M4CuBMi'
  mapping = 'pathname'
  theme = 'light'
  lang = 'en'

[menu]
    [[menu.main]]
      identifier = 'info'
      name = 'Info'
      url = '/contact/'
      weight = 10
    
    [[menu.main]]
        identifier = 'portfolio'
        name = 'Portfolio'
        url = 'https://philippbruhns.com/'
        weight = 10

[caches]
  [[caches.images]]
    dir = ':cacheDir/images'